package com.turbonomic.turbomobile.activity;

import android.app.Dialog;
import android.content.Context;
import android.support.v4.content.ContextCompat;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.text.Html;
import android.text.method.ScrollingMovementMethod;
import android.view.View;
import android.view.WindowManager;
import android.widget.Button;
import android.widget.TextView;
import com.turbonomic.turbomobile.R;

public class WelcomeActivity extends AppCompatActivity {

    Button btnOK;
    TextView txtLicense;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_welcome);
        getSupportActionBar().hide();
        btnOK = findViewById(R.id.btnWelcomeOK);
        txtLicense = findViewById(R.id.txtLicenseLink);

        btnOK.setBackgroundColor(ContextCompat
                .getColor(getApplicationContext(),R.color.colorGreenLight));
        btnOK.setEnabled(false);

        btnOK.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                WelcomeActivity.super.onBackPressed();
            }
        });

        txtLicense.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                showAddItemDialog(view.getContext());
            }
        });
    }

    private void showAddItemDialog(Context c) {
        String licenseText = "<b>Turbonomic</b><br><b>LABS LICENSE AGREEMENT</b><br>Notice to User:<br> This LABS License Agreement (the “Agreement”) is a CONTRACT between you (either an individual or a single entity) (“you” or “Licensee”) and Turbonomic, Inc. (Turbonomic), which covers your use of the LABS Software (as defined below). If you do not agree to the terms of this LABS License Agreement, then do not install or use the LABS Software. By explicitly accepting this Agreement, however, or by installing, copying, downloading, accessing, or otherwise using the LABS Software, you are acknowledging and agreeing to be bound by the following terms.<br>"
                + "1. <b>DEFINITIONS.</b><br>"
                + "(a) “LABS Software” shall mean the unreleased, concept version of Turbonomic’s software, in object form only, excluding any Open Source Software provided with the such software, and the media and Documentation provided by Turbonomic to Licensee and for which Licensee is granted a use license pursuant to this Agreement.<br>"
                + "(b) “Documentation” shall mean the printed and online written reference material furnished to Licensee in conjunction with the LABS Software, including, without limitation, instructions, testing guidelines, and end user guides.<br>"
                + "(c) “Intellectual Property Rights” shall mean all intellectual property rights, including, without limitation, patent, copyright, trademark, and trade secret.<br>"
                + "(d) “Open Source Software” means various open source software components provided with the LABS Software that are licensed to you under the terms of the applicable license agreements included with such open source software components or other materials for the LABS Software.<br>"
                + "(e) “Updates” shall mean a modification, error correction, bug fix, new release, or other update to or for the LABS Software. <br>"
                + "<b>2. LICENSE GRANT, USE AND OWNERSHIP</b><br>"
                + "(a) Limited License. Subject to the terms and conditions of this Agreement, Turbonomic grants to Licensee a non-exclusive, non-transferable license (without the right to sublicense) (i) to use the LABS Software in accordance with the Documentation solely for purposes of internal testing and evaluation on whether or not to license commercial versions of the LABS Software if such commercial versions ever become available, (ii) to use the Documentation provided with the LABS Software in support of Licensee’s authorized use of the LABS Software, and (iii) to copy LABS Software for archival or backup purposes, provided that all titles and trademarks, copyright, and restricted rights notices are reproduced on such copies.<br>"
                + "(b) Evaluation Feedback. The purpose of this limited license is the testing and evaluation of the LABS Software as set forth above. In furtherance of this purpose, Licensee shall provide feedback to Turbonomic concerning the functionality and performance of the LABS Software from time to time as reasonably requested by Turbonomic, including, without limitation, identifying potential errors and improvements. Licensee will provide the requested feedback in a manner that is convenient to Licensee subject to reasonable availability of Licensee’s personnel. Notwithstanding the foregoing, prior to Licensee disclosing to Turbonomic any information under this Agreement that Licensee considers proprietary or confidential, Licensee shall obtain Turbonomic’s prior written approval to disclose such information to Turbonomic, and without such prior written approval from Turbonomic, Licensee shall not disclose any such information to Turbonomic. Turbonomic may use feedback to improve or enhance its products and, accordingly, you hereby grant to Turbonomic a non-exclusive, perpetual, irrevocable, royalty-free, transferable, worldwide right and license, with the right to sublicense, to use, reproduce, disclose, distribute, perform, display, modify, prepare derivative works of and otherwise exploit the feedback and other information without restriction in any manner now known or in the future conceived and to make, use, sell, offer to sell, import and export any product or service that incorporates the feedback and other information.<br>"
                + "(c) Restrictions. Licensee shall not copy or use the LABS Software (including the Documentation) except as expressly permitted in this Agreement. Except to the extent that any applicable mandatory laws prevent Turbonomic’s restraining Licensee from doing so, Licensee will not, and will not permit any third party to, sublicense, rent, copy, modify, create derivative works of, translate, reverse engineer, decompile, disassemble, or otherwise reduce to human perceivable form any portion of the LABS Software or accompanying Documentation. Without limiting the generality of the foregoing, Licensee shall not use the LABS Software for Licensee’s product development or any other commercial purpose. The LABS Software and all performance data and test results, including without limitation, benchmark test results (collectively “Performance Data”), relating to the LABS Software are the Confidential Information of Turbonomic, and will be treated in accordance with the terms of Section 4 of this Agreement. Accordingly, Licensee shall not publish or disclose to any third party any Performance Data relating to the LABS Software.<br>"
                + "(d) Ownership. Turbonomic shall own and retain all right, title and interest in and to the Intellectual Property Rights in the LABS Software, subject only to the limited license expressly set forth in Section 2(a) hereof. Licensee does not acquire any other rights, express or implied, in the LABS Software. ALL RIGHTS NOT EXPRESSLY GRANTED HEREUNDER ARE RESERVED TO TURBONOMIC.<br>"
                + "(e) No Support Services. Turbonomic is under no obligation to support the LABS Software in any way or to provide any Updates to Licensee. In the event Turbonomic, in its sole discretion, supplies any Update to Licensee, the Update shall be deemed LABS Software under this Agreement and shall be subject to the terms and conditions of this Agreement.<br>"
                + "(f) Third-Party Software. The LABS Software may enable a computer to run multiple instances of third-party guest operating systems and application programs. Licensee acknowledges that Licensee is responsible for obtaining any licenses necessary to operate any third-party software, including guest operating systems and application programs.<br>"
                + "(g) Open Source Software. Except Sections 5, 6 and 7, the terms and conditions of this Agreement shall not apply to any Open Source Software accompanying the LABS Software. Any such Open Source Software is provided under the terms of the open source license agreement or copyright notice accompanying such Open Source Software or in the open source licenses file accompanying the LABS Software. 3. TERM AND TERMINATION. Licensee’s rights with respect to the LABS Software will terminate upon the earlier of (a) automatic expiration of the LABS Software based on the system date or (b) termination by Turbonomic, in its sole discretion, of rights to Licensees with respect to the LABS Software provided under this Agreement upon notice on the Turbonomic website. Upon any expiration or termination of rights with respect to the LABS Software under this Agreement, the rights and licenses granted to Licensee under this Agreement shall immediately terminate, and Licensee shall immediately cease using, and will destroy or render practically inaccessible the LABS Software, Documentation, and all other tangible items in Licensee’s possession or control that contain Confidential Information. The rights and obligations of the parties set forth in Sections 2(b), 2(c), 2(d), 2(e), 2(f), 2(g), 3, 4, 5, 6 and 7 shall survive termination or expiration of this Agreement for any reason.<br>"
                + "<b>3. TERM AND TERMINATION.</b><br>"
                + "Licensee’s rights with respect to the LABS Software will terminate upon the earlier of (a) automatic expiration of the LABS Software based on the system date or (b) termination by Turbonomic, in its sole discretion, of rights to Licensees with respect to the LABS Software provided under this Agreement upon notice on the Turbonomic website. Upon any expiration or termination of rights with respect to the LABS Software under this Agreement, the rights and licenses granted to Licensee under this Agreement shall immediately terminate, and Licensee shall immediately cease using, and will destroy or render practically inaccessible the LABS Software, Documentation, and all other tangible items in Licensee’s possession or control that contain Confidential Information. The rights and obligations of the parties set forth in Sections 2(b), 2(c), 2(d), 2(e), 2(f), 2(g), 3, 4, 5, 6 and 7 shall survive termination or expiration of this Agreement for any reason.<br>"
                + "<b>4. CONFIDENTIALITY.</b><br>"
                + "(a) Confidentiality. \"Confidential Information\" shall mean the LABS Software, all information regarding the LABS Software (including any trade secrets, know-how, inventions, techniques, processes, and algorithms embodied in the LABS Software), Documentation, Performance Data, any Updates, and other information provided by Turbonomic to Licensee under this Agreement, whether disclosed orally, in writing, or by examination or inspection, other than information that Licensee can demonstrate (i) was already known to Licensee, other than under an obligation of confidentiality, at the time of disclosure; (ii) was generally available in the public domain at the time of disclosure to Licensee; (iii) became generally available in the public domain after disclosure other than through any act or omission of Licensee; (iv) was subsequently lawfully disclosed to Licensee by a third party without any obligation of confidentiality; or (v) was independently developed by Licensee without use of or reference to any information or materials disclosed by Turbonomic or its suppliers. If Licensee is required to disclose Confidential Information by applicable law or court order, Licensee shall notify Turbonomic of the required disclosure promptly in writing and shall cooperate with Turbonomic in any lawful action to contest or limit the scope of the required disclosure. Confidential Information shall include without limitation any information relating to Turbonomic products, product roadmaps, and other technical, business, financial and product development plans, forecasts and strategies. Licensee shall not use any Confidential Information for any purpose other than as expressly authorized under this Agreement. In no event shall Licensee use the LABS Software or any Confidential Information to develop, manufacture, market, sell, or distribute any product or service, including any Turbonomic products. Licensee shall not disclose any Confidential Information to any third party. Without limiting the foregoing, Licensee shall use at least the same degree of care that it uses to prevent the disclosure of its own confidential information of like importance, but in no event less than reasonable care, to prevent the disclosure of such Confidential Information.<br>"
                + "(b) Additional Confidentiality Restrictions for Highly Confidential LABS Software. For certain LABS Software designated by Turbonomic as highly confidential (“Highly Confidential LABS Software”) in Turbonomic’s correspondence to you regarding this LABS Software or in any Documentation, additional heightened confidentiality restrictions designated below will apply.<br>"
                + "(i) Licensee shall limit dissemination of Highly Confidential LABS Software and related information concerning product features, future technologies and roadmaps only to Information Technology teams and/or software/solutions development teams of Licensee designated by Turbonomic, and only to individuals on those teams who have a need to know the Confidential Information for purposes expressly authorized under this Agreement. For clarity and without limiting the generality of the foregoing, Licensee shall not disseminate any Highly Confidential LABS Software to Licensee's sales and marketing field organizations. Licensee will assign an employee who will be primarily responsible (“Primary Contact”) for ensuring that the terms of this Agreement are complied with.<br>"
                + "(ii) Licensee acknowledges that damages for improper disclosure of Highly Confidential LABS Software or related information concerning product features, future technologies and roadmaps may be irreparable and that monetary damages would be inadequate to compensate Turbonomic for any breach of this Agreement. In the event that Turbonomic reasonably believes that Licensee has disseminated certain of such Highly Confidential LABS Software or related information concerning product features, future technologies and roadmaps to an unauthorized party, Licensee will be immediately removed from Turbonomic’s LABS Software program and will not be permitted to participate in any Turbonomic LABS Software program in the future. Additionally, all rights and licenses granted to Licensee under this Agreement shall immediately terminate in accordance with Section 3 herein (Term and Termination), and (b) in addition to all other remedies available in law or otherwise, Turbonomic is entitled to seek equitable relief, including injunction and preliminary injunction against the threatened breach of this Agreement or the continuation of any such breach.<br>"
                + "<b>5. LIMITATION OF LIABILITY</b><br>"
                + "IT IS UNDERSTOOD THAT THE LABS SOFTWARE IS PROVIDED WITHOUT CHARGE FOR LIMITED EVALUATION PURPOSES. ACCORDINGLY, THE TOTAL LIABILITY OF TURBONOMIC AND ITS LICENSORS ARISING OUT OF OR RELATED TO THIS AGREEMENT SHALL NOT EXCEED $100.00. TO THE FULLEST EXTENT PERMITTED BY LAW, IN NO EVENT SHALL TURBONOMIC OR ITS LICENSORS HAVE LIABILITY FOR ANY INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS PROFITS, BUSINESS INTERRUPTION, OR LOSS OF BUSINESS INFORMATION), HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY (INCLUDING WITHOUT LIMITATION, TORT, STATUTE, CONTRACT OR OTHER), EVEN IF TURBONOMIC AND ITS LICENSORS HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.<br>"
                + "<b>6. WARRANTY DISCLAIMER</b><br>"
                + "IT IS UNDERSTOOD THAT THE LABS SOFTWARE, OPEN SOURCE SOFTWARE, DOCUMENTATION, AND ANY UPDATES MAY CONTAIN ERRORS AND ARE PROVIDED FOR LIMITED EVALUATION ONLY. THE LABS SOFTWARE, THE OPEN SOURCE SOFTWARE, THE DOCUMENTATION, AND ANY UPDATES ARE PROVIDED \"AS IS\" WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE. TURBONOMIC AND ITS LICENSORS SPECIFICALLY DISCLAIM ALL IMPLIED WARRANTIES OF MERCHANTABILITY, NONINFRINGEMENT, AND FITNESS FOR A PARTICULAR PURPOSE. Licensee acknowledges that Turbonomic has not publicly announced the availability of the LABS Software, that such LABS Software may contain features currently under development, that Turbonomic has not promised or guaranteed to Licensee that such LABS Software will be announced or made available to anyone in the future, that Turbonomic has no express or implied obligation to Licensee to announce or introduce the LABS Software, that Turbonomic might not introduce a product similar to or compatible with the LABS Software, and that any version number (if any) referenced is subject to change and does not in any way represent Turbonomic’s commitment to release any product in the future. Accordingly, Licensee acknowledges that any research or development that it performs regarding the LABS Software or any product associated with the LABS Software is done entirely at Licensee’s own risk. Specifically, the LABS Software may contain features, functionality or modules that will not be included in the production version of the LABS Software, if released, or that will be marketed separately for additional fees.<br>"
                + "<b>7. OTHER PROVISIONS</b><br>"
                + "(a) Governing Law. This Agreement, and all disputes arising out of or related thereto, shall be governed by and construed under the laws of the Commonwealth of Massachusetts without reference to conflict of laws principles. All such disputes shall be subject to the exclusive jurisdiction of the state and federal courts located in Boston, Massachusetts, and the parties agree and submit to the personal and exclusive jurisdiction and venue of these courts. The United Nations Convention for the International Sale of Goods shall not apply.<br>"
                + "(b) Export Control. The LABS Software is of United States origin and is provided subject to the U.S. Export Administration Regulations. Diversion contrary to U.S. law is prohibited. Without limiting the foregoing, you agree that (1) you are not, and are not acting on behalf of, any person who is a citizen, national, or resident of, or who is controlled by the government of, Cuba, Iran, North Korea, Sudan, or Syria, or any other country to which the United States has prohibited export transactions; (2) you are not, and are not acting on behalf of, any person or entity listed on the U.S. Treasury Department list of Specially Designated Nationals and Blocked Persons, or the U.S. Commerce Department Denied Persons List or Entity List; and (3) you will not use the LABS Software for, and will not permit the LABS Software to be used for, any purposes prohibited by law, including, without limitation, for any prohibited development, design, manufacture or production of missiles or nuclear, chemical or biological weapons.<br>"
                + "(c) Modification. This is the entire agreement between the parties relating to the subject matter hereof and all other terms are rejected. No waiver or modification of this Agreement shall be valid unless in writing signed by each party. The waiver of a breach of any term hereof shall in no way be construed as a waiver of any other term or breach hereof. If any provision of this Agreement is held by a court of competent jurisdiction to be contrary to law, the remaining provisions of this Agreement shall remain in full force and effect.<br>"
                + "(d) Data Privacy. Licensee agrees that Turbonomic may process technical and related usage information about Licensee’s use of the LABS Software for statistical and analytical purposes. Usage information is collected strictly for internal statistical and analytical purposes for the development of Turbonomic products and services. Licensee understands that any log files generated in order to obtain support from Turbonomic may contain sensitive, confidential or personal information. Licensee should consider obfuscating any logs before sending them to Turbonomic. Turbonomic’s privacy policy (http://www.Turbonomic.com/help/privacy.html) shall apply.<br>"
                + "<b>8. ASSIGNMENT</b><br>"
                + "Licensee shall not assign this Agreement or any rights or obligations hereunder, directly or indirectly, by operation of law, merger, acquisition of stock or assets, or otherwise, without the prior written consent of Turbonomic. Any attempted assignment or transfer in violation of the foregoing will be null and void. Subject to the foregoing, this Agreement shall inure to the benefit of and be binding upon the parties and their respective successors and permitted assigns.<br>"
                + "<b>9. CONTACT INFORMATION</b><br>"
                + "If you have any questions about this Agreement, please direct all correspondence to: Turbonomic, Inc., 500 Boylston Street, Seventh Floor, Boston, MA 02116, United States of America or email info@Turbonomic.com. Turbonomic is a trademark of Turbonomic, Inc. and is registered in the U.S. and numerous other countries.";

        final Dialog dialog = new Dialog(c);
        dialog.setContentView(R.layout.layout_license_dialog);
        TextView text =  dialog.findViewById(R.id.textLicenseContents);
        text.setMovementMethod(new ScrollingMovementMethod());
        text.setText(Html.fromHtml(licenseText));
        Button dialogButton =  dialog.findViewById(R.id.dialogLicenseOK);
        dialogButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                dialog.dismiss();
                btnOK.setBackgroundColor(ContextCompat
                        .getColor(getApplicationContext(),R.color.colorMainBg2));
                btnOK.setEnabled(true);
            }
        });
        dialog.getWindow().getAttributes().width = WindowManager.LayoutParams.MATCH_PARENT;
        dialog.show();
    }
}
